version: "3.7"

services:

  gateway:
      image: gateway:1
      restart: on-failure
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      expose:
        - 8079
      ports:
        - 8079:8079
  tracer:
    image: jaegertracing/all-in-one
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  db-catalogue:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: coolgame
      POSTGRES_USER: postgres
      POSTGRES_DB: catalogue
    volumes:
      - /var/lib/postgresql/catalogue
    expose:
      - 5432
    ports:
      - 5433:5432
  rabbit:
    image: rabbitmq:3.8.2-management-alpine
    restart: on-failure
    environment:
      RABBITMQ_PASSWORD : guest
      RABBITMQ_USERNAME: guest
    volumes:
      - /var/lib/rabbitmq/data
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
  admin:
    image: adminer
    restart: on-failure
    ports:
    - 8080:8080
    depends_on:
      - db-catalogue
      - db-order
  catalogue:
    image: catalogue:1
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      JAEGER_AGENT_HOST: tracer
      SPRING_RABBITMQ_HOST : rabbit
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-catalogue:5432/catalogue
    expose:
      - 8081
    depends_on:
      - db-catalogue
      - rabbit
      - eureka-server
      - tracer
    ports:
      - 8081:8081
    links:
      - db-catalogue
      - rabbit
      - eureka-server
      - tracer
  order:
    image: order:1
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_RABBITMQ_HOST : rabbit
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-order:5432/orders
      JAEGER_AGENT_HOST: tracer
    expose:
      - 8082
    depends_on:
      - db-order
      - rabbit
      - eureka-server
      - tracer
    ports:
      - 8082:8082
    links:
      - eureka-server
      - db-order
      - rabbit
      - tracer
  db-order:
    image: postgres:12.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/order
    environment:
      POSTGRES_PASSWORD: coolgame
      POSTGRES_USER: postgres
      POSTGRES_DB: orders
    expose:
      - 5432
    ports:
      - 5432:5432
  eureka-server:
    image: discovery:1
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    expose:
      - 8761
    ports:
      - 8761:8761

